// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMx-gnGvW5MuMUUNmcudhdzr_5UZBAvLo',
    appId: '1:226417939597:web:80a070ef0f2f54d9dbfec4',
    messagingSenderId: '226417939597',
    projectId: 'quankydangky',
    authDomain: 'quankydangky.firebaseapp.com',
    storageBucket: 'quankydangky.firebasestorage.app',
    measurementId: 'G-S5VVDMVWYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCndAyO-sF3q3KPd5g9azTX-2xJ5XgzfSU',
    appId: '1:226417939597:android:32e5881c322cff55dbfec4',
    messagingSenderId: '226417939597',
    projectId: 'quankydangky',
    storageBucket: 'quankydangky.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMx-gnGvW5MuMUUNmcudhdzr_5UZBAvLo',
    appId: '1:226417939597:web:975a409393c0ac9fdbfec4',
    messagingSenderId: '226417939597',
    projectId: 'quankydangky',
    authDomain: 'quankydangky.firebaseapp.com',
    storageBucket: 'quankydangky.firebasestorage.app',
    measurementId: 'G-S2CYZR7VE7',
  );
}
